approvedGitRepositories:
  - "**"

defaultSemverRangePrefix: ""

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

packageExtensions:
  "@next/eslint-plugin-next@*":
    peerDependencies:
      eslint: ">=9"
